build:
  environment:
    php: 8.1
    timezone: Europe/Paris

  nodes:
    tests:
      tests:
        override:
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover
